language: c
compiler:
 - gcc
 - clang
notifications:
    email: false
script:
    - make prefix=`pwd`/local install
    - make check
    - make utf8proc_data.c.new && (diff utf8proc_data.c.new utf8proc_data.c > /dev/null)
    - mkdir build_static
    - cd build_static
    - cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON
    - make
    - mkdir ../build_shared
    - cd ../build_shared
    - cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=ON
    - make
